import imagea from '../images/1_1.jpg';
import imageb from '../images/2.png';
import imagec from '../images/3.png';
import imaged from '../images/4.png';

const productData = [
    { id: 1, 
    image1: 'https://i.imgur.com/j3MSp8U.jpeg',
    image2: 'https://i.imgur.com/erg1epG.jpeg',
    image3: 'https://i.imgur.com/a5qC9ky.jpeg',
    image4: 'https://i.imgur.com/aDJ0eav.jpeg',
    category:'Lips' , 
    subcategory:'Best Seller',
    title: 'LIPSMART - Lip Balm & Hydrating Lip Treatment (Medical Grade) - 0.33 Fl. Oz', 
    description: 'Powerful Hydration for Dry Lips' ,
     price1:'$32.00',size1:'0.33 Fl Oz (Pack of 1)',
     price2:'$60.0',size2:'0.33 Fl oz (Pack of 2)',
     price3:'$88.0',size3:'0.33 Fl oz (Pack of 3)',
    about:'Lipsmart draws in the natural water attracting components to boost hydration and retain moisture. Our proprietary formula has five powerful and effective ingredients using the highest quality humectants and lipids, to keep you hydrated longer Replenishes your lips with ingredients they need to heal from within to eliminate dryness, cracking, flaking, and deflation in 60 seconds it also contains peptides to help stimulate natural hyaluronic acidBrightens & revives the color of drying, fading lipstickBio active blends of pineapple, coconut, lemon and peach. Nourishes, brighten, softens and helps maintain elasticity',
    descriptiontitle1:'Hydrated up to 4 hours',
    description1:'Not Your Average Lip Balm. Our product works totally different! Its proprietary formula delivers 5 powerful and effective ingredients, using the highest quality humectants and lipids to keep you hydrated up to 4 hours without the need to reapply.',
    descriptiontitle2:'Extreme Moisture',
    description2:'Typical lip balms only temporarily condition the lips, leaving a drying after-effect when they wear off. LIPSMART uses 5 Powerful Actives to continuously draw in moisture and lock it in, providing continuous hydration and long-lasting relief with noticeable results in just 60 seconds.',
    descriptiontitle3:'LIPSMART',
    description3:'LIPSMART slows down moisture loss, preventing water molecules from evaporating. Your lips will appear healthier, nourished and fuller, filling out fine lines, cracks and eliminating flakiness.',
    funneldescription:'LIPSMART is a proven and effective solution for all dry lip concerns. Our proprietary formula delivers intense, medical-grade hydration clinically proven to provide visible results in just 60 seconds. LIPSMART replenishes your lips with the ingredients they need to heal from within to eliminate dryness, cracking, flaking, fine lines, and deflation immediately.'


},
{ 
    id: 2, 
    image1: 'https://i.imgur.com/1PH6Daa.jpeg',
    image2: 'https://i.imgur.com/GCrljkm.jpeg',
    image3: 'https://i.imgur.com/0TCAjgh.jpeg',
    image4: 'https://i.imgur.com/24QnrMj.jpeg', 
    title: 'K18 Leave-In Molecular Hair Mask, Repairs Dry or Damaged Hair', 
    description: 'Repairs Dry or Damaged Hair',
    price1:'$29.00',size1:'0.51 Fl Oz (Pack of 1)',
    price2:'$56.0',size2:'5.07 Fl oz (Pack of 1)',
    price3:'$75.0',size3:'50 ml  (Pack of 1)',
    category: 'Hair Care', 
    subcategory: 'Best Seller', 
    about: '', 
    descriptiontitle1: 'Description', 
    description1: 'This leave-in treatment mask works on the molecular level to reverse hair damage in just 4 minutes. It tackles daily damage with immediate and lasting results to restore strength, softness, smoothness and bounce to hair', 
    descriptiontitle2: 'BENEFITS', 
    description2: 'Our K18PEPTIDE™ repairs hair at a molecular level across multiple types of bonds, restoring hair health for all', 
    descriptiontitle3: 'Suggested Use', 
    description3: 'Shampoo, do not condition. Towel-dry thoroughly. Apply 1-3 pumps of K18 mask & massage through hair. Let treatment sit in the hair for 4 minutes. Do not rinse', 
    funneldescription: 'Our K18PEPTIDE™ repairs hair at a molecular level across multiple types of bonds, restoring hair health for all' 
},
{ 
    id: 3, 
    image1: 'https://i.imgur.com/j3MSp8U.jpeg', 
    image1: 'https://i.imgur.com/1PH6Daa.jpeg',
    image2: 'https://i.imgur.com/GCrljkm.jpeg',
    image3: 'https://i.imgur.com/0TCAjgh.jpeg',
    image4: 'https://i.imgur.com/24QnrMj.jpeg', 
    title: 'Eufora Beautifying Serum Nourishing Treatment Oil 4 Fl.Oz', 
   
    description: 'Description for product 3',
    category: 'Best Seller', 
    subcategory: '', 
    about: '', 
    descriptiontitle1: 'Hair Care Solution', 
    description1: 'This lightweight serum is safe for use on hair, skin, and scalp. Non-greasy, lightweight and fast absorbing. Delivers superb moisturization.', 
    descriptiontitle2: 'Softness And Strength ', 
    description2: 'Deeply heal, smooth and restore luster to damaged, dry and coarse hair l will have your hair feeling nourished and renewed so you can have the confidence.', 
    descriptiontitle3: 'Key Ingredients', 
    description3: ' Eufora\'s blend of Cranberry, Neem, Kukui, and Argan oils are rich in omega essential acids, vitamins and minerals, delivering superb moisturizing and antioxidant benefits.', 
    funneldescription: '' 
},
{ 
    id: 4, 
    image1: 'https://i.imgur.com/2KaPXHf.jpeg', 
    title: 'Eufora Beautifying Serum Nourishing Treatment Oil 4 Fl.Oz', 
    description: 'Description for product 4',
    price1:'$40.00',size1:'$10/ Fl oz',
    category: 'Hair Care', 
    subcategory: 'Best Seller', 
    descriptiontitle1: 'Hair Care Solution', 
    description1: 'This lightweight serum is safe for use on hair, skin, and scalp. Non-greasy, lightweight and fast absorbing. Delivers superb moisturization.', 
    descriptiontitle2: 'Softness And Strength ', 
    description2: 'Deeply heal, smooth and restore luster to damaged, dry and coarse hair l will have your hair feeling nourished and renewed so you can have the confidence.', 
    descriptiontitle3: 'Key Ingredients', 
    description3: ' Eufora\'s blend of Cranberry, Neem, Kukui, and Argan oils are rich in omega essential acids, vitamins and minerals, delivering superb moisturizing and antioxidant benefits.', 
    funneldescription: 'Repair For Dry Damaged Hair - repairing & hydrating therapy for color treated & damaged hair. revive, restore your mane from scalp to roots & heal split ends.' 
},
{ 
    id: 5, 
    image: imagea, 
    title: 'Product 5', 
    description: 'Description for product 5',
    category: '', 
    subcategory: 'Body Care', 
    about: '', 
    descriptiontitle1: '', 
    description1: '', 
    descriptiontitle2: '', 
    description2: '', 
    descriptiontitle3: '', 
    description3: '', 
    funneldescription: '' 
},
{ 
    id: 6, 
    image: imageb, 
    title: 'Product 6', 
    description: 'Description for product 6',
    category: '', 
    subcategory: 'Head Care', 
    about: '', 
    descriptiontitle1: '', 
    description1: '', 
    descriptiontitle2: '', 
    description2: '', 
    descriptiontitle3: '', 
    description3: '', 
    funneldescription: '' 
},
{ 
    id: 7, 
    image: imageb, 
    title: 'Product 6', 
    description: 'Description for product 6',
    category: '', 
    subcategory: 'Head Care', 
    about: '', 
    descriptiontitle1: '', 
    description1: '', 
    descriptiontitle2: '', 
    description2: '', 
    descriptiontitle3: '', 
    description3: '', 
    funneldescription: '' 
},
{ 
    id: 8, 
    image: imageb, 
    title: 'Product 6', 
    description: 'Description for product 6',
    category: '', 
    subcategory: 'Head Care', 
    about: '', 
    descriptiontitle1: '', 
    description1: '', 
    descriptiontitle2: '', 
    description2: '', 
    descriptiontitle3: '', 
    description3: '', 
    funneldescription: '' 
},
];

export default productData;
